spring.application.name=duri-front
spring.profiles.active=${ACTIVE_PROFILE:dev}

# JWT (???)
jwt.issuer=duri-auth
jwt.public-key=${JWT_PUBLIC_KEY}

# Cookie (???)
web.cookie.domain=
web.cookie.access-path=/
web.cookie.access-max-age=86400