openai.api.key=${OPENAI_KEY}
gemini.api.key=${GEMINI_KEY}

# Gateway Server URL
gateway.server.url=https://api.duri.asia

# MariaDB
spring.datasource.url=jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${MARIA_DB}?useUnicode=true&characterEncoding=utf8mb4
spring.datasource.username=${MARIA_USERNAME}
spring.datasource.password=${MARIA_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.jdbc.timezone=Asia/Seoul

# JWT
jwt.issuer=duri-auth
jwt.public-key=${JWT_PUBLIC_KEY}

# Cookie
web.cookie.domain=.duri.asia
web.cookie.is-secure=true
web.cookie.same-site=None
web.cookie.access-path=/
web.cookie.access-max-age=86400

# TODO: URL 수정 필요
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@eureka.duri.asia/eureka
eureka.instance.prefer-ip-address=true

# Logging
logging.file.name=/logs/app.log
logging.logback.rollingpolicy.max-file-size=50MB
logging.logback.rollingpolicy.max-history=14
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger - %msg%n