server.port=8080

# JPA Setting
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Local DEV DB Connection
spring.datasource.url=${MARIADB_LOCAL_URL}
spring.datasource.username=${MARIADB_LOCAL_USERNAME}
spring.datasource.password=${MARIADB_LOCAL_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver