openai.api.key=${OPENAI_KEY}
gemini.api.key=${GEMINI_KEY}

# Auth Server URL
auth.server.url=https://auth.duri.asia

# MariaDB
spring.datasource.url=jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${MARIA_DB}?useUnicode=true&characterEncoding=utf8mb4
spring.datasource.username=${MARIA_USERNAME}
spring.datasource.password=${MARIA_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.jdbc.timezone=Asia/Seoul

# JWT
jwt.issuer=duri-auth
jwt.public-key=${JWT_PUBLIC_KEY}

# Cookie
web.cookie.domain=.duri.asia
web.cookie.is-secure=true
web.cookie.same-site=None
web.cookie.access-path=/
web.cookie.access-max-age=86400