spring.application.name=duri-front
spring.profiles.active=${ACTIVE_PROFILE:dev}

# JWT (???)
jwt.issuer=duri-auth
jwt.public-key=${JWT_PUBLIC_KEY}

# Cookie (???)
web.cookie.domain=
web.cookie.access-path=/
web.cookie.access-max-age=86400

# MariaDB
spring.datasource.url=jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${MARIA_DB}
spring.datasource.username=${MARIA_USERNAME}
spring.datasource.password=${MARIA_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.jdbc.timezone=Asia/Seoul