server.port=8081

# JPA Setting
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Local DEV DB Connection
spring.datasource.url=${MARIADB_LOCAL_URL}
spring.datasource.username=${MARIADB_LOCAL_USERNAME}
spring.datasource.password=${MARIADB_LOCAL_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

jwt.public-key=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOeNF86seo+IqAG6FD+7SWIka5O8XQZ4o50DbCeIsPP+IG93KJJIyUQuhKtm3BVkBJsgP3On24GmavDtp7U8pCA==
MARIADB_LOCAL_PASSWORD=lim!@#0112
MARIADB_LOCAL_URL=jdbc:mariadb://localhost:3307/duri
MARIADB_LOCAL_USERNAME=root